### ISSUE TITLE
Android build release fails 

### ISSUE THREAD

**Issue by Ammarlio** [vyshakh/react-native-uaepass#1]
First of all thanks for adding UAE Pass to react native.

Android Studio Version: Android Studio Giraffe | 2022.3.1 Patch 1

I am facing an issue when releasing Android build.

**Direct local .aar file dependencies are not supported when building an AAR**
<img width="392" alt="Screenshot 2024-02-21 at 9 49 16 PM" src="https://github.com/vyshakh/react-native-uaepass/assets/36266791/be15dcb9-6b9e-412f-9f2a-83c168a56757">

any idea?

**Comment by vyshakh** [comment]
@Ammarlio  Thank you for reporting this issue. I'm looking into it.  Please let me know if you find any solution to fix this issue

**Comment by vyshakh** [comment]
./gradlew assembleRelease  🔴 Failing . Getting error " Direct local .aar file dependencies are not supported when building an AAR" 
./gradlew bundleRelease  🟢  
./gradlew app:assembleRelease 🟢

**Comment by Ammarlio** [comment]
@vyshakh thank you so much for your prompt reply.

I will try it today.

**Comment by Ammarlio** [comment]
./gradlew bundleRelease 🟢
./gradlew app:assembleRelease 🔴
I am facing the same error.


<img width="572" alt="Screenshot 2024-02-24 at 2 58 47 PM" src="https://github.com/vyshakh/react-native-uaepass/assets/36266791/974caebb-d2e4-4ca9-b59d-4dee1a5af4dd">

**Comment by vyshakh** [comment]
@Ammarlio  try this version https://github.com/vyshakh/react-native-uaepass/releases/tag/v1.0.5
// Add below code to android/build.gradle file. Paste it above the last line -  "apply plugin..."
```
  allprojects {
      repositories{
          flatDir{
            dirs "$rootDir/../node_modules/react-native-uaepass/android/libs"
          }
      }
  }

```
