### ISSUE TITLE
iOS: locale not changing language to *Arabic* when app is not installed on device.

### ISSUE THREAD

**Issue by Yousafzubair991** [vyshakh/react-native-uaepass#12]
Hi @vyshakh ,

Recently UAE PASS highlighted an issue where they mentioned that when the app's language is changed to 'AR' the UAE PASS webview (when the UAE PASS app is not installed on the device scenario) should also be changed to AR,

I tried updating the UAE PASS Config but it only worked on Android, not iOS. (screenshots attached)
Please let me know if I'm missing something.

Thanks and best regards.

My UAEPASS Config passed: 
**{
    "clientId": <client_id>,
    "clientSecret": <client_secret>,
    "env": "production",
    "failureHost": "uaePassFailure",
    "locale": "ar",
    "nonce": <nonce>,
    "prompt": "login",
    "redirectURL": <url_here>,
    "response_type": "code",
    "scheme": <scheme_here>,
    "scope": "urn:uae:digitalid:profile",
    "state": <state>,
    "successHost": "uaePassSuccess",
    "ui_locales": "ar"
}**

![Screenshot_1731567974](https://github.com/user-attachments/assets/f74bdf36-a32a-4258-9056-edc4804406a5)
![Simulator Screenshot - iPhone 15 - 2024-11-14 at 11 06 04](https://github.com/user-attachments/assets/650ae644-2ea5-455f-87e0-f0f2467eca18)

**Comment by vyshakh** [comment]
@Yousafzubair991  Thank you for trying this module and reporting the bug. I've implemented a fix for this issue. Please try the latest release, version 1.0.14.

**Comment by Yousafzubair991** [comment]
> @Yousafzubair991 Thank you for trying this module and reporting the bug. I've implemented a fix for this issue. Please try the latest release, version 1.0.14.

@vyshakh, thank you so much for your prompt response.
