### ISSUE TITLE
[Android] Empty Screen Appears When Creating New Account on Android

### ISSUE THREAD

**Issue by hasan642** [vyshakh/react-native-uaepass#2]
Thank you for the amazing implementation! However, I'm encountering an issue on the Android platform. When attempting to create a new account, an empty screen appears instead of the expected registration form or process.

check this video:

https://github.com/vyshakh/react-native-uaepass/assets/32715055/205cf69c-0c46-44c4-b247-8ae7262b9f96

**Comment by vyshakh** [comment]
Hi Alwaneh

Thank you for reporting this issue.
I will check it out and get back to you.
Meanwhile please make sure that you used the correct configuration and no
network security policies blocking the requests. Are you getting same
results when you connected to wifi and mobile data?

Please let me know the below details
1. Your app react native version
2. Are you testing on device or simulator


Regards
Vyshakh

**Comment by hasan642** [comment]
Hello @vyshakh,
yes network is connected well,
i'm using expo bare with the following details:

- react-native version: 0.73.5
- expo: 50
- react-native-uaepass: 1.0.5

what do you mean with the correct configuration, i've added the client id and the client secret!
any thing else?

Thank you.

**Comment by vyshakh** [comment]
@hasan642  Please note that, this module will not work with expo. I will update the Readme and mention this.
Please use react-native cli to try this module. 
Thank you

**Comment by hasan642** [comment]
please note that i'm working in expo bare not managed, it shouldn't work even with expo bare?

and if yes how it basically works with some issues!

**Comment by vyshakh** [comment]
@hasan642 I haven't got a chance to test it on expo bare. I will look into this issue soon.

**Comment by hasan642** [comment]
I will try to react-native vanilla, and back to you.

but to check something, this is params that I passed to the module:
`const UAEPassConfig = {
  env: "staging",
  clientId: "sandbox_stage",
  redirectURL: "com.test://uaepass",
  successHost: "uaePassSuccess",
  failureHost: "uaePassFailure",
  scheme: "uaepassfrejnaapp",
  scope: "urn:uae:digitalid:profile",
  locale: "en",
};`

there is something weird here?

Thank you for your support.

**Comment by hasan642** [comment]
Hello @vyshakh ,
Please note that this issue also occurs in your example on GitHub.

**Comment by vyshakh** [comment]
Steps to run the example on Android

```
- git clone git@github.com:vyshakh/react-native-uaepass.git
- cd react-native-uaepass/
- yarn
- yarn example android
- Use your UAEpass configuration (UAEPassConfig) in example/src/App.tsx
- Use your manifestPlaceholders in in example/android/app/build.gradle
- yarn example android
```

**Comment by hasan642** [comment]
please try to run it to see what i mean, it is not working.
the same issue in the video hapened.
