### ISSUE TITLE
[!] Unable to read the license file `LICENSE` for the spec `UAEPassClient (1.4)`

### ISSUE THREAD

**Issue by meetwithtaha** [vyshakh/react-native-uaepass#3]
[!] A license was specified in podspec `UAEPassClient` but the file does not exist - /Users/tahamuhammad/Library/CloudStorage/OneDrive-EY/Desktop/ReactJs/office/old-repo/my-navigator/node_modules/react-native-uaepass/ios/LocalPods/UAEPassClient/LICENSE

version:    "react-native-uaepass": "^1.0.5",

I am not able to run app in iOS facing above issue. @vyshakh

**Comment by meetwithtaha** [comment]
<img width="1637" alt="Screenshot 2024-04-27 at 1 16 44 AM" src="https://github.com/vyshakh/react-native-uaepass/assets/55944722/c54416ec-93ed-48aa-b642-aa4b8c5713ee">

**Comment by vyshakh** [comment]
Fixed
