### ISSUE TITLE
iOS crash when try to logout by logout function from UAEPass

### ISSUE THREAD

**Issue by hasan642** [vyshakh/react-native-uaepass#6]
scenario:
login to my app via login UAEPass function, then reopen the application, then try to logout, the app will crash on iOS only.

lib version: 1.09
rn version: 0.73.5

Thank you.

**Comment by Yousafzubair991** [comment]
Same happening to me

**Comment by git-azhar** [comment]
> hasan642

did you fixed ?

**Comment by hasan642** [comment]
no i think the plugin creator should resolve it

**Comment by vyshakh** [comment]
Please try Release 1.0.11 https://github.com/vyshakh/react-native-uaepass/releases/tag/v1.0.11 @hasan642

**Comment by hasan642** [comment]
i did but does not work on 11 also @vyshakh
