### ISSUE TITLE
Onclick of links in uaepass webview shows empty screen

### ISSUE THREAD

**Issue by Hariprakash010501** [vyshakh/react-native-uaepass#8]
In android, When i try to click any link in the uaepass webview, shows blank screen and it was working fine in ios.

I have attached the screen recording for reference
https://github.com/user-attachments/assets/f07f33fd-d701-44e6-a959-8fc85be63af4

lib version: 1.09
rn version: 0.73.5
environment: staging

**Comment by mdazhar780** [comment]
@Hariprakash010501 did you fixed that issue ?

**Comment by mdazhar780** [comment]
i'm facing issue in ios but android it is working fine my side could you please assist me to install npm in my ios it will be very helpfull

**Comment by Hariprakash010501** [comment]
Even i am not able to figure out why this is not happening in ios @mdazhar780

**Comment by mdazhar780** [comment]
@Hariprakash010501 in your ios is working ?

**Comment by Hariprakash010501** [comment]
Yes it is @mdazhar780  not in android

**Comment by mdazhar780** [comment]
@Hariprakash010501 could you please assist me for integration in ios i'll check android because my android is working

**Comment by Hariprakash010501** [comment]
@mdazhar780 Sure, we can connect and resolve it

**Comment by mdazhar780** [comment]
@Hariprakash010501 could you please share your whatsapp or contact no so we can connect through. Monday my office will resume.

**Comment by mdazhar780** [comment]
@Hariprakash010501 Could you please share your contact so we can connect and fix those issue please.

**Comment by Hariprakash010501** [comment]
@mdazhar780  Please drop a mail to hariprakashraja18@gmail.com

**Comment by vyshakh** [comment]
@Hariprakash010501  Thank you for reporting the bug, Could you please try this version [1.0.10](https://github.com/vyshakh/react-native-uaepass/releases/tag/v1.0.10 )

**Comment by Hariprakash010501** [comment]
Its working now @vyshakh . Thanks a lot for considering and fixing it soon

Closing the issue....
