### ISSUE TITLE
Android App to Web Scenario 

### ISSUE THREAD

**Issue by mdazhar786** [vyshakh/react-native-uaepass#9]
Dear Mr. @vyshakh 

Greeting

Currently in Android App to web scenarios, the UAE PASS login identifier page is not opening in full-screen mode. We kindly request to update & show the Android Login identifier page in full-screen mode similar to iOS.

Thank You.
![androida2w](https://github.com/user-attachments/assets/c2477b0f-a2a7-45c2-a158-1a06e2776faf)
![ios a2w](https://github.com/user-attachments/assets/cc13b4e3-8f50-4e26-8de3-4e59d0733e6a)

**Comment by vyshakh** [comment]
I tried some styling but am still not able to remove the margins. We can change the black transparency to white using the code below.

#### android/app/src/main/AndroidManifest.xml
```
-  <activity android:name="com.uaepass.LoginActivity"  android:launchMode="singleTask" android:exported="true" android:parentActivityName=".MainActivity" >
+  <activity android:name="com.uaepass.LoginActivity" android:launchMode="singleTask" android:exported="true" android:parentActivityName=".MainActivity" android:theme="@style/UAEPassWebviewThemeFullscreen" >
```

#### and then add style to android/app/src/main/res/values/styles.xml
```
<style name="UAEPassWebviewThemeFullscreen" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowFullscreen">true</item>
    <item name="android:windowIsFloating">false</item>
    <item name="android:windowBackground">@android:color/white</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:backgroundDimEnabled">false</item>
</style>
```

If you find a better fix for this issue, please raise a pull request.
